{
  {% if initialDelaySeconds != null %}
  "initialDelaySeconds": {{ initialDelaySeconds }},
  {% endif %}

  {% if periodSeconds != null %}
  "periodSeconds": {{ periodSeconds }},
  {% endif %}

  {% if timeoutSeconds != null %}
  "timeoutSeconds": {{ timeoutSeconds }},
  {% endif %}

  {% if failureThreshold != null %}
  "failureThreshold": {{ failureThreshold }},
  {% endif %}

  {% if successThreshold != null %}
  "successThreshold": {{ successThreshold }},
  {% endif %}

  "httpGet": {
    {% if httpHeaders != null }
    "httpHeaders": [
      {% for header in httpHeaders %}
      { "name": "{{ header.name }}", "value": "{{ header.value }}" } {% if not loop.last %} , {% endif %}
      {% endfor %}
    ],
    {% endif %}

    {% if scheme != null %}
    "scheme": "{{ scheme }}",
    {% endif %}
    "port": "{{ port }}",
    "path": "{{ path }}"
  }
}
