{
  "initialDelaySeconds": {{ initialDelaySeconds }},
  "tcpSocket": {
    "port": {{ port }}
  },

  {% if periodSeconds != null %}
  "periodSeconds": {{ periodSeconds }},
  {% endif %}

  {% if timeoutSeconds != null %}
  "timeoutSeconds": {{ timeoutSeconds }},
  {% endif %}

  {% if successThreshold != null %}
  "successThreshold": {{ successThreshold }},
  {% endif %}

  {% if failureThreshold != null %}
  "failureThreshold": {{ failureThreshold }}
  {% endif %}
}
