name: Build operator flavor

on:
  push:
    branches:
    - gen-manifests

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Xmx2g -Xms2g

jobs:
  branch-build:
    env:
      GRADLE_ARGS: -Partifactory_user=${{secrets.ARTIFACTORY_USER}} -Partifactory_password=${{secrets.ARTIFACTORY_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install Java 8 for cross-compilation support. Setting it up before
      # Java 11 means it comes later in $PATH (because of how setup-java works)
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        id: build
        run: |
          ./gradlew version --quiet
          version=$(cat build/version | head -1)
          echo "==== Building version: $version"
          ./gradlew -PenableCrossCompilerPlugin=true installDist javadoc --stacktrace
          echo "##[set-output name=version;]$version"
      - name: Create Docker image
        run: |
          docker build . -t docker.io/armory/halyard:${{ steps.build.outputs.version }} -f Dockerfile.slim
      - name: Push images
        id: push_step
        run: |
          docker tag docker.io/armory/halyard:${{ steps.build.outputs.version }} armory-docker-local.jfrog.io/armory/halyard:${{ steps.build.outputs.version }}
          echo "Logging in to jfrog"
          docker login -u ${{ secrets.ARTIFACTORY_USER }} -p "${{ secrets.ARTIFACTORY_PASSWORD }}" armory-docker-local.jfrog.io
          docker push armory-docker-local.jfrog.io/armory/halyard:${{ steps.build.outputs.version }}

          echo "Logging in to dockerhub"
          docker login -u ${{ secrets.DOCKERHUB_USER }} -p "${{ secrets.DOCKERHUB_PASSWORD }}" docker.io
          docker tag docker.io/armory/halyard:${{ steps.build.outputs.version }} docker.io/armory/halyard:operator-dev
          docker push docker.io/armory/halyard:${{ steps.build.outputs.version }}
          docker push docker.io/armory/halyard:operator-dev

          echo "##[set-output name=image;]armory/halyard:${{ steps.build.outputs.version }}"
      - name: Upload to artifactory
        run: |
          ./gradlew artifactPublish $GRADLE_ARGS
      - name: Run Security Scan
        uses: armory-io/aquasec-scan-action@master
        with:
          username: ${{ secrets.AQUA_USER }}
          password: ${{ secrets.AQUA_PASSWORD }}
          url: https://aquasec.armory.io
          image: ${{ steps.push_step.outputs.image }}
          registry: Artifactory
